### ISSUE TITLE
Multiple learners with cvtune = FALSE and cvperf = FALSE

### ISSUE THREAD

**Issue by bdwilliamson** [benkeser/slapnap#11]
We currently allow multiple learners to be specified when cvtune and cvperf are both FALSE. The default behavior is to select the learner that was specified first (e.g., if learners="lasso;rf", then we'll use "lasso") and then run as if only a single learner were specified. 

Do we want to have this functionality, or if multiple learners are entered to we want to force either cvtune or cvperf to be TRUE?

**Comment by benkeser** [comment]
This is an intentional use case. Where we just want to use slapnap to fit a super learner, but with a limited library. `cvtune` would add in multiple versions of algorithms to the library; `cvperf` would then estimate the cross-validated performance.

**Comment by benkeser** [comment]
Will leave issue open until the added default behavior is removed.

**Comment by bdwilliamson** [comment]
Fixed: the output below is the result of setting learners="lasso;rf", cvtune=FALSE, cvperf=FALSE
![slapnap_report_nocv_multilearner_fixed](https://user-images.githubusercontent.com/13205756/77566879-8aff9c00-6e83-11ea-973a-0a3d8beab6a7.png)
