### ISSUE TITLE
Remaining things to do

### ISSUE THREAD

**Issue by benkeser** [benkeser/slapnap#12]
@bdwilliamson 

__Report:__
- [ ] add table/bullet list to executive summary, with: # sequences pulled from CATNAP, # sequences with complete data used in analysis, class balance (if binary), other descriptive statistics for continuous data, etc. (BW)
- [ ] place stars next to ranks with statistically significant p-values in Table 1.3 (BW)
- [X] Make sure that Figure 2.1 (and others like it) have spaces in the correct places in caption (DB)
- [ ] Change feature groups (y-axis in vimp plot) to have sensible names; make sure that x-axis and title don't get cut off (BW)
- [x] Legends on sens/resis plots (DB)
- [ ] make nomenclature consistent in all areas of report (e.g., biological importance everywhere instead of "population importance") (BW)

__Documentation:__
- [ ] bookdown vignette(s) (DB)
- [ ] other documentation? (DB)

**Comment by bdwilliamson** [comment]
- [x] bulleted list in executive summary
- [x] place stars next to ranks with statistically significant p-values in Table 1.3
- [x] Change feature groups (y-axis in vimp plot) to have sensible names
- [x] Make sure x-axis and title of vimp plots don't get cut off
- [x] Make nomenclature consistent in all areas of report

**Comment by benkeser** [comment]
Is vignette all that is left of this to do?

**Comment by bdwilliamson** [comment]
Yes -- I couldn't edit your list so I had to make my own.
