### ISSUE TITLE
options for controlling what is saved

### ISSUE THREAD

**Issue by benkeser** [benkeser/slapnap#13]
@bdwilliamson Could we add an option that dictates what gets returned?

Right now, I am recommended that the `-v` option be used to mount the `/home/output` to a local directory for retrieval of results. Could we add a short cleanup script that checks the option for what the user wants to save (possible inputs could be `"data"` (analysis data set), `"learner"` (return fitted R object), `"report"` (default). Anything else? `"figures"` to return the images from the report?

**Comment by bdwilliamson** [comment]
That sounds good -- I included in the latest Dockerfile two options (return_full_sl_obj, return_analysis_dataset) that I'll bundle into a new option called "return" that takes a semicolon-separated string with inputs "data", "learner", "report", "figures", and "vimp" (the variable importance objects).
